version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'academy_db'
      MYSQL_USER: 'academy_user'
      MYSQL_PASSWORD: 'strong_password'
      MYSQL_ROOT_PASSWORD: 'very_strong_root_password'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
